### ISSUE TITLE
score map results unexpected

### ISSUE THREAD

**Issue by Mary-Wall** [usnistgov/SDNist#4]
![Picture1](https://user-images.githubusercontent.com/57052739/149598635-f770ca00-be92-4ff6-b0c0-a4cd1bebc2e9.png)
![Picture2](https://user-images.githubusercontent.com/57052739/149598642-5f38ff1e-7500-4f1c-9bfc-81dad2577f87.png)

1.  Built synthetic data DPsynth.csv with SDNist/examples/DPSyn with
`!python main.py`

2.  Produced html map with: 
  
`!python -m sdnist DPSynthCensus`

**Comment by glothe** [comment]
Hello Mary,

1. Currently, the heat map only works on the IL-OH dataset, i.e the public one. The `SDNist/examples/DPSyn/main.py` example attempts to reproduce the score of the leaderboard (which is computed on a private dataset). We could add a warning if someone attempts to visualize the private dataset.
2. Unless the DPSyn examples outputs a .csv file called "DPSynthCensus" (with no extension), I'm surprised this command does not throw an error. The syntax is actually `python -m sdnist [.csv filename of the synthetic data]`. Also note that by default, the synthetic data is evaluated against the public dataset.

**Comment by Mary-Wall** [comment]
Hi Gary, 

Thank you for pointing out DPSyn does not output a file called "DPSynthCensus"!  I should have mentioned - prior to running` python -m sdnist DPSynthCensus` I built synthetic of ACS with DPSyn in a notebook with:
```
import argparse
import numpy as np
import yaml
from loguru import logger
from dataloader.DataLoader import *
from dataloader.RecordPostprocessor import RecordPostprocessor
from method.sample_parallel import Sample
from config.path import *
import sdnist
import matplotlib.pyplot as plt
with open(CONFIG_DATA, 'r') as f:
    config = yaml.load(f, Loader=yaml.BaseLoader)
# dataloader initialization
dataloader = DataLoader()
dataloader.load_data()
# sample
eps, delta, sensitivity = 1, 2.5e-4, 7
logger.info(f'working on eps={eps}, delta={delta}, and sensitivity={sensitivity}')
synthesizer = Sample(dataloader, eps, delta, sensitivity)
synthetic_data = synthesizer.synthesize()
# preprocess
postprocessor = RecordPostprocessor()
#synthetic_data = postprocessor.post_process(synthetic_data, args.config, dataloader.decode_mapping)
#logger.info("post-processed synthetic data")
synthetic_data = postprocessor.post_process(synthetic_data, "./config/data.yaml", dataloader.decode_mapping)
logger.info("post-processed synthetic data")
private_data, schema = sdnist.census(public=False)
#print(sdnist.score(private_data, synthetic_data))
synthetic_data.to_csv('DPsynthCensus')
```

**Comment by glothe** [comment]
That explains point 2 then! 
Regarding point 1, DPSyn actually pretrains on the public data (= IL_OH dataset) in order to train with DP on the private data. 
We have two options
- slightly change the data loader of DPSyn so that it trains on the public data only (and outputs results for the IL_OH dataset). Unfortunately, given that it already pretrains with no privacy constraints, the results will not be DP
- update the html viewer so that it works on all 3 datasets. This would be the best option, but I don't really know how to do that right now. The code to create the visuals only instantiates a Jinja template which was provided during the original challenge, I'm only reusing it and I don't know who made it.

**Comment by garyhowarth** [comment]
We are working to expand the visualizer functionality to both public and private datasets. I am leaving this issue open until that process is complete.
